### ISSUE TITLE
Improvements to documentation 

### ISSUE THREAD

**Issue by ErinCain** [CVPIA-OSC/fallRunDSM#7]
- [x] Find paper for Colvin et al. (2018), add to aws bucket and DSM model docs 
- [x] Find paper for (Newman and Brandes (2010)) , add to aws bucket and DSM model docs file:///C:/Users/Erin%20Cain/Downloads/Hierarchical_Modeling_of_Juvenile_Chinook_Salmon_S.pdf
- [x] Find sources for all surv_juv_outmigration_sac_delta() arguments and add to documentation 
- [x] Rmarkdown of empirical model fit params analyses

**Comment by ergz** [comment]
found papers, and converted "Find sources for all surv_juv_outmigration_sac_delta() arguments and add to documentation" to its own issue
